export const CARGAR_TRABAJOS = 'CARGAR_TRABAJOS';
export const AGREGAR_ROL_FILTRO = 'AGREGAR_ROL_FILTRO';
export const ACTUALIZAR_TRABAJOS_FILTRADOS = 'ACTUALIZAR_TRABAJOS_FILTRADOS';
export const LIMPIAR_TRABAJOS = 'LIMPIAR_TRABAJOS';
export const REMOVER_FILTRO = 'REMOVER_FILTRO';
